# Generated by Django 4.0.5 on 2022-06-13 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applied_developers',
            field=models.ManyToManyField(null=True, related_name='developers', to=settings.AUTH_USER_MODEL, verbose_name='Applied Developer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Accepted Developer'),
        ),
    ]
