# Generated by Django 4.0.5 on 2022-06-13 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_alter_job_applied_developers_alter_job_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applied_developers',
            field=models.ManyToManyField(blank=True, null=True, related_name='developers', to=settings.AUTH_USER_MODEL, verbose_name='Applied Developer'),
        ),
    ]
