# Generated by Django 3.2.13 on 2022-06-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_developer_remove_user_is_recruiter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='history',
            field=models.ManyToManyField(blank=True, null=True, related_name='_accounts_user_history_+', to='accounts.User'),
        ),
    ]
