# Generated by Django 3.2.13 on 2022-06-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='history',
            field=models.ManyToManyField(blank=True, null=True, related_name='_accounts_user_history_+', to='accounts.User'),
        ),
    ]
