# Generated by Django 4.0.5 on 2022-06-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_cv_alter_user_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_job',
            field=models.BooleanField(default=False),
        ),
    ]
