# Generated by Django 4.0.5 on 2022-06-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_in_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='in_job',
        ),
    ]
