# Generated by Django 4.0.5 on 2022-06-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='username',
            new_name='user',
        ),
    ]
